### ISSUE TITLE
email comments from DFM 2020-05-15

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaussianProductRefactor#5]

**Comment by adrn** [comment]
- [x] In footnote 5 (and throughout): I'm confused by that definition of "tensor". Tensors won't generally be square, non-negative, positive semi-definite, or matrices. I think that the term is being misused here. Call them "covariance matrices" or just square, non-negative, positive-definite matrices!
- [x] At the end of section 1: "they are generally GPs with a trivial kernel function but a non-trivial mean function" is one way of thinking about it, but we often actual use this the other way around. The *marginalized* likelihood will be GP with a trivial *mean* and (somewhat) non-trivial *covariance* (A . Lambda . A^T). This is what we derived in Luger et al.
- [x] I feel like the "solution" stops a little short. I know how to do the integral of the RHS of Eq. 11 over theta, but I think it might be useful to explicitly comment on it here.
- [x] In "implementation notes" you could be a bit more forceful about solve vs inv and replace "in general" with "always"...
