### ISSUE TITLE
sign off on or change large-scale document formatting

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaussianProductRefactor#7]

**Comment by adrn** [comment]
I hate to admit it, but I like it - I say keep the new format!

**Comment by adrn** [comment]
@davidwhogg But: I think we should move the figures out of the margin...

**Comment by davidwhogg** [comment]
Yes! The only teensy weensy issue is that I think mparhack may be allergic to floats.... But I'm willing to try
